filetype plugin on
filetype indent on
syntax on

set viminfo='10,<100,:100,%,n~/.cache/vim/viminfo
set number
set smartindent
set hidden

set ignorecase
set smartcase

set incsearch
set hlsearch

set noswapfile
set nobackup

set shiftwidth=0
set tabstop=4
set noexpandtab
