filetype plugin on
syntax on

set viminfo='10,<100,:100,%,n~/.cache/vim/viminfo
set number
set smartindent
set hidden
set ignorecase
set smartcase
set incsearch
set hlsearch
set tabstop=3
set noswapfile
set nobackup
